### ISSUE TITLE
Keys for CI publishing

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-crypto#1]
@rossabaker whenever you have a chance. Thanks!

**Comment by armanbilge** [comment]
Oh, and while you're at it if you wouldn't mind doing the same over in https://github.com/typelevel/bobcats/issues/1 as well I'd be much obliged 😄

**Comment by rossabaker** [comment]
Not tested, but there.

**Comment by armanbilge** [comment]
Thanks!

**Comment by armanbilge** [comment]
Seems to have worked 👍
